In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/covid19-dataset/owid-covid-data (1).csv

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
ori_data = pd.read_csv('/kaggle/input/covid19-dataset/owid-covid-data (1).csv')

In [4]:
ori_data.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,population,population_density,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,24-02-2020,5,5,0.0,0,0,0.0,...,40099462,54.422,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,25-02-2020,5,0,0.0,0,0,0.0,...,40099462,54.422,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,26-02-2020,5,0,0.0,0,0,0.0,...,40099462,54.422,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,27-02-2020,5,0,0.0,0,0,0.0,...,40099462,54.422,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,28-02-2020,5,0,0.0,0,0,0.0,...,40099462,54.422,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511

In [5]:
ori_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189999 entries, 0 to 189998
Data columns (total 34 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   iso_code                    189999 non-null  object
 1   continent                   179435 non-null  object
 2   location                    189999 non-null  object
 3   date                        189999 non-null  object
 4   total_cases                 189999 non-null  int64
 5   new_cases                   189999 non-null  int64
 6   new_cases_smoothed          189999 non-null  float64
 7   total_deaths                189999 non-null  int64
 8   new_deaths                  189999 non-null  int64
 9   new_deaths_smoothed         189999 non-null  float64
 10  total_cases_per_million     189999 non-null  float64
 11  new_cases_per_million       189999 non-null  float64
 12  total_deaths_per_million    189999 non-null  float64
 13  reproduction_rate           189999 non-null  float64
 14  hosp_patients               189999 non-null  int64
 15  total_tests                 189999 non-null  int64
 16  positive_rate               189999 non-null  float64
 17  tests_units                 189999 non-null  object
 18  total_vaccinations          189999 non-null  int64
 19  people_vaccinated           189999 non-null  int64
 20  people_fully_vaccinated     189999 non-null  int64
 21  total_boosters              189999 non-null  int64
 22  new_vaccinations            189999 non-null  int64
 23  stringency_index            189999 non-null  float64
 24  population                  189999 non-null  int64
 25  population_density          189999 non-null  float64
 26  aged_65_older               189999 non-null  float64
 27  aged_70_older               189999 non-null  float64
 28  gdp_per_capita              189999 non-null  float64
 29  cardiovasc_death_rate       189999 non-null  float64
 30  diabetes_prevalence         189999 non-null  float64
 31  hospital_beds_per_thousand  189999 non-null  float64
 32  life_expectancy             189999 non-null  float64
 33  human_development_index     189999 non-null  float64
dtypes: float64(17), int64(12), object(5)
memory usage: 49.3+ MB

In [6]:
ori_data.isnull().sum()
data = ori_data

In [7]:
data['date'] = pd.to_datetime(data['date'])

In [8]:
data['Month'] = data['date'].apply(lambda date: date.month)
data['Year'] = data['date'].apply(lambda date:date.year)

In [9]:
data.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence,hospital_beds_per_thousand,life_expectancy,human_development_index,Month,Year
0,AFG,Asia,Afghanistan,2020-02-24,5,5,0.0,0,0,0.0,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020
1,AFG,Asia,Afghanistan,2020-02-25,5,0,0.0,0,0,0.0,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020
2,AFG,Asia,Afghanistan,2020-02-26,5,0,0.0,0,0,0.0,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020
3,AFG,Asia,Afghanistan,2020-02-27,5,0,0.0,0,0,0.0,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020
4,AFG,Asia,Afghanistan,2020-02-28,5,0,0.0,0,0,0.0,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020

In [10]:
data.drop(columns = 'date', inplace = True)
data.head()

,iso_code,continent,location,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,...,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence,hospital_beds_per_thousand,life_expectancy,human_development_index,Month,Year
0,AFG,Asia,Afghanistan,5,5,0.0,0,0,0.0,0.125,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020
1,AFG,Asia,Afghanistan,5,0,0.0,0,0,0.0,0.125,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020
2,AFG,Asia,Afghanistan,5,0,0.0,0,0,0.0,0.125,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020
3,AFG,Asia,Afghanistan,5,0,0.0,0,0,0.0,0.125,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020
4,AFG,Asia,Afghanistan,5,0,0.0,0,0,0.0,0.125,...,2.581,1.337,1803.987,597.029,9.59,0.5,64.83,0.511,2,2020

In [11]:
colrcode = [(31,119,180), (225,127,14),\
            (44, 160, 44), (214, 39, 40), \
             (148, 103, 189),  (140, 86, 75), \
             (227, 119, 194), (127, 127, 127), \
             (188, 189, 34), (23, 190, 207)]

for i in range(len(colrcode)):  
    r, g, b = colrcode[i]  
    colrcode[i] = (r / 255., g / 255., b / 255.,)